config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :abets do
    collection {post :import}
  end

  resources :courses_users do

  end

  resources :courses do
    collection {post :import }
  end
  resources :users do
    collection { post :import }
  end

  root 'courses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/abet.rb
class Abet < ApplicationRecord
  require 'csv'
  validates_uniqueness_of :name

  has_many :abet_grades
  has_many :courses_users, through: :abet_grades

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      begin
        Abet.create! row.to_hash
      rescue ActiveRecord::RecordInvalid => invalid
        puts invalid.record.errors
      rescue ActiveModel::UnknownAttributeError => invalid
        puts invalid.record.errors
      end
    end
  end

end

app/controllers/abets_controller.rb
class AbetsController < ApplicationController
  before_action :set_abet, only: [:show, :edit, :update, :destroy]

  # GET /abets
  # GET /abets.json
  def index
    @abets = Abet.all
  end

  # GET /abets/1
  # GET /abets/1.json
  def show
  end

  # GET /abets/new
  def new
    @abet = Abet.new
  end

  # GET /abets/1/edit
  def edit
  end

  # POST /abets
  # POST /abets.json
  def create
    @abet = Abet.new(abet_params)

    respond_to do |format|
      if @abet.save
        format.html { redirect_to @abet, notice: 'ABET Criteria was successfully created.' }
        format.json { render :show, status: :created, location: @abet }
      else
        format.html { render :new }
        format.json { render json: @abet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abets/1
  # PATCH/PUT /abets/1.json
  def update
    respond_to do |format|
      if @abet.update(abet_params)
        format.html { redirect_to @abet, notice: 'ABET Criteria was successfully updated.' }
        format.json { render :show, status: :ok, location: @abet }
      else
        format.html { render :edit }
        format.json { render json: @abet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abets/1
  # DELETE /abets/1.json
  def destroy
    @abet.destroy
    respond_to do |format|
      format.html { redirect_to abets_url, notice: 'ABET Criteria was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    if params[:file].nil?
      redirect_to abets_path, notice: "File Not Found!"
    else
      Abet.import(params[:file])
      redirect_to abets_path, notice: "File Uploaded Successfully. ABET Criteria with duplicate Descriptions will be skipped."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_abet
      @abet = Abet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def abet_params
      params.require(:abet).permit(:name, :description, :poor, :acceptable, :exceeds)
    end
end

app/helpers/abets_helper.rb
module AbetsHelper
end

app/views/abets/_form.html.erb
<%= form_with(model: abet, local: true) do |form| %>
  <% if abet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(abet.errors.count, "error") %> prohibited this abet from being saved:</h2>

      <ul>
      <% abet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <br>
  <div class="actions">
    <%= form.submit "Update ABET"%>
  </div>
<% end %>

app/views/abets/edit.html.erb
<h1>Editing ABET Criteria</h1>

<%= render 'form', abet: @abet %>

<%= link_to 'Show', @abet %> |
<%= link_to 'Back', abets_path %>

app/views/abets/index.html.erb
<h1>ABET Criteria</h1>
<% if @abets.count > 0 %>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @abets.order(:name).each do |abet| %>
      <tr>
        <td><%= abet.name %></td>
        <td><%= abet.description %></td>
        <td><%= link_to 'Show', abet %></td>
        <% if current_account.admin? %>
        <td><%= link_to 'Edit', edit_abet_path(abet) %></td>
        <td><%= link_to 'Destroy', abet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
          </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <h4>No ABET Criteria Exist</h4>
<% end %>
<% if current_account.admin? %>
<h4><%= link_to 'New ABET Criteria', new_abet_path %></h4>
  <% end %>
<hr>
<h2>Bulk Upload ABET Criteria</h2>
<% if current_account.admin? %>
<%= form_tag import_abets_path, multipart: true do %>
  <p><%= file_field_tag :file %></p>
  <p><%= submit_tag "Import ABET Criteria" %></p>
<% end %>
  <% else %>
  <p>Only Admins can bulk upload!</p>
  <% end %>
<hr>
<h4><a href="abet_template.csv" download>Download Template</a></h4>
<h4><a href="abet_test_data.csv" download>Download Example Data</a></h4>

<h5>Tip: Assign ABET Criteria in the Grades menu!</h5>

app/views/abets/new.html.erb
<h1>New ABET Criteria</h1>

<%= render 'form', abet: @abet %>

<%= link_to 'Back', abets_path %>

app/views/abets/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @abet.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @abet.description %>
</p>

<hr>
<% if current_account.admin? %>
<%= link_to 'Edit', edit_abet_path(@abet) %> |
  <% end %>
<%= link_to 'Back', abets_path %>