config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :abets do
    collection {post :import}
  end

  resources :courses_users do

  end

  resources :courses do
    collection {post :import }
  end
  resources :users do
    collection { post :import }
  end

  root 'courses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  require 'csv'
  validates_uniqueness_of :email

  has_many :courses_users
  has_many :courses, through: :courses_users

  has_many :abets_courses, :dependent => :delete_all
  accepts_nested_attributes_for :abets_courses, allow_destroy: true


  def full_name
    "#{fname} #{lname}"
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
    begin
      User.create! row.to_hash
    rescue ActiveRecord::RecordInvalid => invalid
      puts invalid.record.errors
    rescue ActiveModel::UnknownAttributeError => invalid
      puts invalid.record.errors
    end
  end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Faculty was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Faculty was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Faculty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    if params[:file].nil?
      redirect_to users_path, notice: "File Not Found!"
    else
      User.import(params[:file])
      redirect_to users_path, notice: "File Uploaded Successfully. Faculty with duplicate emails will be skipped."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:lname, :fname, :title, :office, :email, :phone, :role)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lname, :'Last Name' %><br>
    <%= form.text_field :lname %>
  </div>

  <div class="field">
    <%= form.label :fname, 'First Name' %><br>
    <%= form.text_field :fname %>
  </div>

  <div class="field">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :office %><br>
    <%= form.text_field :office %>
  </div>

  <div class="field">
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %><br>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.select(:role, ['Administrator','User'])%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing Faculty</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Faculty</h1>
<% if @users.count > 0 %>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Office</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Role</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.order(:fname).each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.title %></td>
        <td><%= user.office %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <% if user.role == 'Administrator' %>
          <td>Admin</td>
          <% else %>
        <td><%= user.role %></td>
          <% end %>
        <td><%= link_to 'Show', user %></td>
        <% if current_account.admin? %>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <h4>No Faculty Exist</h4>
<% end %>

<% if current_account.admin? %>
<h4><%= link_to 'New Faculty', new_user_path %></h4>
  <% end %>
<hr>
<h2>Bulk Upload Faculty</h2>
<% if current_account.admin? %>
<%= form_tag import_users_path, multipart: true do %>
  <p><%= file_field_tag :file %></p>
  <p><%= submit_tag "Import Faculty" %></p>
<% end %>
  <% else %>
  <p> Only Admins can bulk upload!</p>
  <% end %>
<hr>
<h4><a href="faculty_template.csv" download>Download Template</a></h4>
<h4><a href="faculty_test_data.csv" download>Download Example Data</a></h4>
<h5>Tip: Assign Faculty by editing Courses!</h5>

app/views/users/new.html.erb
<h1>New Faculty</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Last Name:</strong>
  <%= @user.lname %>
</p>

<p>
  <strong>First Name:</strong>
  <%= @user.fname %>
</p>

<p>
  <strong>Title:</strong>
  <%= @user.title %>
</p>

<p>
  <strong>Office:</strong>
  <%= @user.office %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<br>
<h2>Assigned Courses</h2>

<% if @user.courses.count > 0 %>
<table class="table">
  <thead>
  <tr>
    <th>Course Number</th>
    <th>Description</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @user.courses.each do |course| %>
    <tr>
      <td><%= course.course_number %></td>
      <td><%= course.description %></td>
      <td><%= link_to 'Show', course %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<br>
<% else %>
<h4>No Assigned Courses</h4>
<% end %>

<% if current_account.admin? %>
<%= link_to 'Edit', edit_user_path(@user) %> |
  <% end %>
<%= link_to 'Back', users_path %>