config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :abets do
    collection {post :import}
  end

  resources :courses_users do

  end

  resources :courses do
    collection {post :import }
  end
  resources :users do
    collection { post :import }
  end

  root 'courses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/courses_user.rb
class CoursesUser < ApplicationRecord
  belongs_to :course
  belongs_to :user

  has_many :abet_grades, :dependent => :delete_all
  has_many :abets, through: :abet_grades
  accepts_nested_attributes_for :abet_grades, allow_destroy: true
  accepts_nested_attributes_for :abets, allow_destroy: true

end

app/controllers/courses_users_controller.rb
class CoursesUsersController < ApplicationController
  before_action :set_courses_user, only: [:show, :edit, :update, :destroy]

  # GET /courses_users
  # GET /courses_users.json
  def index
    @courses_users = CoursesUser.all
  end

  # GET /courses_users/1
  # GET /courses_users/1.json
  def show
  end

  # GET /courses_users/new
  def new
    @courses_user = CoursesUser.new
  end

  # GET /courses_users/1/edit
  def edit
  end

  # POST /courses_users
  # POST /courses_users.json
  def create
    @courses_user = CoursesUser.new(courses_user_params)

    respond_to do |format|
      if @courses_user.save
        format.html { redirect_to @courses_user, notice: 'Courses user was successfully created.' }
        format.json { render :show, status: :created, location: @courses_user }
      else
        format.html { render :new }
        format.json { render json: @courses_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses_users/1
  # PATCH/PUT /courses_users/1.json
  def update
    respond_to do |format|
      if @courses_user.update(courses_user_params)
        format.html { redirect_to @courses_user, notice: 'Courses user was successfully updated.' }
        format.json { render :show, status: :ok, location: @courses_user }
      else
        format.html { render :edit }
        format.json { render json: @courses_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses_users/1
  # DELETE /courses_users/1.json
  def destroy
    @courses_user.destroy
    respond_to do |format|
      format.html { redirect_to courses_users_url, notice: 'Courses user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_courses_user
      @courses_user = CoursesUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def courses_user_params
      params.require(:courses_user).permit(:user_id, :course_id, :abet_ids => [], :grade => [], abet_grades_attributes: [:id, :courses_user_id, :abet_id, :poor, :acceptable, :exceeds, :poor_grade, :grade, :exceeds_grade])
      #params.require(:courses_user).
    end
end

app/helpers/courses_users_helper.rb
module CoursesUsersHelper
end

app/views/courses_users/_form.html.erb
<%= form_with(model: courses_user, local: true) do |form| %>
  <% if courses_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(courses_user.errors.count, "error") %> prohibited this courses_user from being saved:</h2>

      <ul>
      <% courses_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <strong>Course:</strong>
    <%= @courses_user.course.course_number %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @courses_user.user.full_name %>
  </p>
  <h2>ABET Criteria</h2>
  <% if Abet.all.count > 0 %>
    <%= form.collection_check_boxes(:abet_ids, Abet.all, :id, :name) do |box| %>
      <div class="row">
        <%= box.label(class: "check_box") do %>
          <div>
            &nbsp; <%= box.check_box(class: "check_box") %>
            &nbsp; <%= box.object.name %>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <h4>No ABET Criteria Exists</h4>
  <% end %>
  <br>
  <div class="actions">
    <%= form.submit "Update Criteria"%>
  </div>

<% end %>

app/views/courses_users/edit.html.erb
<h1>Assigning ABET Criteria</h1>

<%= render 'form', courses_user: @courses_user %> <br>

<%= link_to 'Update Grades', @courses_user, :"data-turbolinks" => false  %>

app/views/courses_users/index.html.erb
<h1>ABET Criteria Grades</h1>
<% if @courses_users.count > 0 %>
<table class="table">
  <thead>
    <tr>
      <th>Course<br>Number</th>
      <th>Faculty<br>Member</th>
      <th class="text-center">Criteria<br>Assigned</th>
      <th class="text-center">Poor<br>Grades</th>
      <th class="text-center">Acceptable<br>Grades</th>
      <th class="text-center">Exceeds<br>Grades</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses_users.joins(:course).order('courses.course_number asc').each do |courses_user| %>
      <tr>
        <td><%= courses_user.course.course_number %></td>
        <td><%= courses_user.user.full_name %></td>
        <td class="text-center"><%= courses_user.abet_grades.count %></td>
        <td class="text-center"><%= courses_user.abet_grades.sum(:poor_grade) %></td>
        <td class="text-center"><%= courses_user.abet_grades.sum(:grade) %></td>
        <td class="text-center"><%= courses_user.abet_grades.sum(:exceeds_grade) %></td>
        <td><%= link_to 'View Grades', courses_user, :"data-turbolinks" => false  %></td>
        <% if current_account.admin? %>
        <td><%= link_to 'Assign Criteria', edit_courses_user_path(courses_user) %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <br><h4>No Faculty assignments exist, add more by editing Courses!</h4>
<% end %>

app/views/courses_users/new.html.erb
<h1>New Courses User</h1>

<%= render 'form', courses_user: @courses_user %>

<%= link_to 'Back', courses_users_path %>

app/views/courses_users/show.html.erb
<h3>Course Assignment</h3>

<p>
  <strong>Course:</strong>
  <%= @courses_user.course.course_number %>
</p>

<p>
  <strong>User:</strong>
  <%= @courses_user.user.full_name %>
</p>


<h3>ABET Criteria</h3>
<body data-turbolinks="false">
<% if @courses_user.abets.count > 0 %>
  <% if current_account.admin? %>
  <table class="table">
    <thead>
    <tr>
      <th>ABET Name</th>
      <th class="text-center">Poor<br>Threshold</th>
      <th class="text-center">Acceptable<br>Threshold</th>
      <th class="text-center">Exceeds<br>Threshold</th>
      <th class="text-center">Poor<br>Students</th>
      <th class="text-center">Acceptable<br>Students</th>
      <th class="text-center">Exceeds<br>Students</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @courses_user.abets.each do |abet| %>
      <tr>
        <td><%= abet.name %></td>

          <%= form_for @courses_user, url: {action: "update" } do |f| %>
            <%= f.fields_for :abet_grades do |ff| %>
              <% if ff.object.abet_id == abet.id %>
              <td class="text-center"><%= ff.number_field :poor, {min: 0, max:100} %>%</td>
              <td class="text-center"><%= ff.number_field :acceptable, {min: 0, max:100} %>%</td>
              <td class="text-center"><%= ff.number_field :exceeds, {min: 0, max:100} %>%</td>
              <td class="text-center"><%= ff.number_field :poor_grade, {min: 0, max: 100}%></td>
              <td class="text-center"><%= ff.number_field :grade, {min: 0, max: 100}%></td>
              <td class="text-center"><%= ff.number_field :exceeds_grade, {min: 0, max: 100}%></td>
              <td><%= ff.submit "Update Grade" %></td>
              <% end %>
            <% end %>
          <% end %>
          </tr>

    <% end %>
    </tbody>
  </table>
    <% else %>

    <table class="table">
      <thead>
      <tr>
        <th>ABET Name</th>
        <th class="text-center">Poor</th>
        <th class="text-center">Acceptable</th>
        <th class="text-center">Exceeds Expectations</th>
        <th class="text-center">Grade</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @courses_user.abet_grades.each do |abet| %>
        <tr>
          <td><%= abet.abet.name %></td>
          <td  class="text-center"><%= abet.poor %>%</td>
          <td  class="text-center"><%= abet.acceptable %>%</td>
          <td  class="text-center"><%= abet.exceeds %>%</td>
          <td  class="text-center">
           <% if abet.grade != nil %>
            <%= abet.grade %>%
              <% else %>
            <p>No Grade</p>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <% end %>
<% else %>
  <h4>No Assigned ABET Criteria</h4>
<% end %>
</body>
<% if current_account.admin? %>
<hr>
<h4><%= link_to 'Assign ABET Criteria', edit_courses_user_path(@courses_user) %></h4>
<% end %>