config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :abets do
    collection {post :import}
  end

  resources :courses_users do

  end

  resources :courses do
    collection {post :import }
  end
  resources :users do
    collection { post :import }
  end

  root 'courses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">
<div class="container">
  <div class="col-lg-12" style="background-color:white">
  <head>
    <title>Johnny Russell's Semester Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>


        <ul class="nav navbar-nav navbar-left">

    <% if current_account %>
      User: <%= current_account.email %>
      <%= link_to 'Sign Out', destroy_account_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign Up', new_account_registration_path %>
      <%= link_to 'Sign In', new_account_session_path %>
    <% end %>

        </ul>

    <h1 style="font-weight:bold;color:white;background-color:lightskyblue;outline-style:solid;padding:20px">Course Management System</h1>
    <h3 style="outline-color:lightskyblue;outline-style:solid;padding:10px">
    <%= link_to "Faculty", users_path %> &nbsp; &nbsp;
    <%= link_to "Courses", courses_path %> &nbsp; &nbsp;
      <%= link_to "Criteria", abets_path %> &nbsp; &nbsp;
      <%= link_to "Grades", courses_users_path %>
    </h3>


  <body style="background-color:lightskyblue">
  <span class="notice"><%= notice %></span>
  <span class="alert"><%= alert %></span>
  <%= yield %>
  <br><br><br><br>
  </body>
    </div>
  </div>
</html>